# -*- coding: utf-8 -*-
"""SalesPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RDh_6KvrXUDxEqaQIxsOOnUr4g0pOy9E

# Sales Prediction using Python

- involves forecasting the amount of a product that customers will purchase, taking into advertising platform selection.
- in businesses that offer products or services, the role of Data scientists is crucial for predicting future sales.
- utilizing machine learning techniques to analyze and interpret data, allowing them to make informed decisions regarding advertising costs
- by leveraging these predictions, business can optimize their advertising strategies and maximize sales potential


Let's analyze this dataset of sales prediction using machine learning in Python.
"""

from google.colab import drive
drive.mount('/content/drive/')

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

dataset = pd.read_csv('/content/drive/MyDrive/SalesPrediction/advertising.csv')
dataset.head()

dataset.tail()

print(dataset.isnull().sum())

"""We have no null values so let's look at correlation between features (tv with sales, radio with sales, newspaper with sales)"""

print(dataset.corr())
plt.style.use('seaborn-whitegrid')
plt.figure(figsize=(10, 10))
sns.heatmap(dataset.corr())
plt.show()

X = np.array(dataset.drop(['Sales'], 1))
y = np.array(dataset['Sales'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

data = pd.DataFrame(data={'Predicted Sales':y_pred.flatten()})
data

"""That's one way to predict sales.

Let's look at one feature independent with sales. Let's say 'TV'.

"""

dataset.plot.scatter(x='TV', y='Sales')
x = dataset[['TV']]
y = dataset[['Sales']]

model = LinearRegression()
model.fit(x, y)
model.predict(x)

# extract coefficient and intercept and draw a line with that intercept and slope. Give the same graph as above.
print(model.intercept_)
print(model.coef_)
X_new = pd.DataFrame()
X_new = np.linspace(5, 300, num=300)
y_new = [(model.coef_ * i + model.intercept_) for i in X_new]
y_new = np.array(y_new).reshape(-1, 1)
# print(X_new.shape)
# print(y_new.shape)

dataset.plot.scatter(x='TV', y='Sales')
plt.plot(X_new, y_new, c='r')

# Same plot as above.

"""Now let's test a prediction given all 3 costs of advertising.

Fit a linear regression model that predicts the sale price using given cost of TV advertising, cost of newspaper advertising, and cost of radio advertising. Interpret the coefficients. Then, use your fitted model to predict the sale of a 200.5 cost of TV advertising, 50 cost of radio advertising, and 75 cost of newspaper advertising.
"""

X_train = dataset[['TV', 'Radio', 'Newspaper']]
y_train = dataset[['Sales']]

test = pd.DataFrame({'TV':200.5, 'Radio':50.0, 'Newspaper':75.0}, index=[0])

Model = LinearRegression()
Model.fit(X_train, y_train)
print(Model.coef_)
Model.predict(X=test)

"""The coefficients are rate of change for TV cost is 0.054, 0.107 for Radio, and 0.00033 for newspaper. For cost of newspaper advertisement at 200.5, 50.0 cost for radio, and 75.0 cost for newspaper, the predicted sales price is 20.91

"""

