# -*- coding: utf-8 -*-
"""IrisFlowerClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7tKxTBz_uJ_SvRuH4p9DSoRObYqB04I

# Iris Flower Classification
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Datasets/IRIS.csv')
df.head()

# end of dataset; 150 rows of data
df.tail()

"""## About Dataset
### Context

The Iris flower data set is a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems. It is sometimes called Anderson's Iris data set because Edgar Anderson collected the data to quantify the morphologic variation of Iris flowers of three related species. The data set consists of 50 samples from each of three species of Iris (Iris Setosa, Iris virginica, and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

This dataset became a typical test case for many statistical classification techniques in machine learning such as support vector machines

### Content
- The dataset contains a set of 150 records under 5 attributes - Petal Length, Petal Width, Sepal Length, Sepal width and Class(Species).

####  Acknowledgements
This dataset is free and is publicly available at the UCI Machine Learning Repository.
"""

df.describe()

print(df['species'].unique())

"""### Model"""

from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()

x = df.drop('species', axis=1)
y = df['species']

"""### KNN"""

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)

preds = knn.predict(x_test)

accuracy = knn.score(x_test, y_test)
print(accuracy)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, preds)
cm

x_test_new = np.array([[6.5, 3.1, 5.3, 1.5]])
pred = knn.predict(x_test_new)
pred

x_test_new = np.array([[3.5, 1.1, 3.3, 2.2]])
pred = knn.predict(x_test_new)
pred

"""### Naive bayes classifier"""

# naive bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
model_preds = model.predict(x_test)
# print(list(model_preds))

accuracy = model.score(x_test, y_test)
print(accuracy)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, model_preds)
cm

x_test_new = np.array([[6.5, 3.1, 5.3, 1.5]])
pred = model.predict(x_test_new)
pred

x_test_new = np.array([[3.5, 1.1, 3.3, 2.2]])
pred = model.predict(x_test_new)
pred